### ISSUE TITLE
Running download_data.py throws a ValueError: Couldn't cast options: list<item: string>

### ISSUE THREAD

**Issue by Xuanaaa** [thu-coai/SafetyBench#8]
Traceback (most recent call last):
  File "D:\CVTECode\qatools\.venv\lib\site-packages\datasets\builder.py", line 1894, in _prepare_split_single
    writer.write_table(table)
  File "D:\CVTECode\qatools\.venv\lib\site-packages\datasets\arrow_writer.py", line 570, in write_table
    pa_table = table_cast(pa_table, self._schema)
  File "D:\CVTECode\qatools\.venv\lib\site-packages\datasets\table.py", line 2324, in table_cast
    return cast_table_to_schema(table, schema)
  File "D:\CVTECode\qatools\.venv\lib\site-packages\datasets\table.py", line 2282, in cast_table_to_schema
    raise ValueError(f"Couldn't cast\n{table.schema}\nto\n{features}\nbecause column names don't match")
ValueError: Couldn't cast
options: list<item: string>
  child 0, item: string
question: string
id: int64
category: string
to
{'Offensiveness': [{'question': Value(dtype='string', id=None), 'options': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None), 'answer': Value(dtype='int64', id=None)}], 'Unfairness and Bias': [{'question': Value(dtype='string', id=None), 'options': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None), 'answer': Value(dtype='int64', id=None)}], 'Physical Health': [{'question': Value(dtype='string', id=None), 'options': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None), 'answer': Value(dtype='int64', id=None)}], 'Mental Health': [{'question': Value(dtype='string', id=None), 'options': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None), 'answer': Value(dtype='int64', id=None)}], 'Illegal Activities': [{'question': Value(dtype='string', id=None), 'options': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None), 'answer': Value(dtype='int64', id=None)}], 'Ethics and Morality': [{'question': Value(dtype='string', id=None), 'options': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None), 'answer': Value(dtype='int64', id=None)}], 'Privacy and Property': [{'question': Value(dtype='string', id=None), 'options': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None), 'answer': Value(dtype='int64', id=None)}]}
because column names don't match

**Comment by nonstopfor** [comment]
Does this issue still exist now?
